namespace :app_config do
  desc "Generate TypeScript types from AppConfig frontend schema"
  task generate: :environment do
    require "fileutils"

    schema = AppConfig.frontend_json_schema
    output_dir = Rails.root.join("app/frontend/common")
    output_file = output_dir.join("app-config.ts")

    FileUtils.mkdir_p(output_dir)

    properties = schema[:properties].map do |name, _type|
      "  #{name}: string;"
    end.join("\n")

    typescript_content = <<~TYPESCRIPT
      // this type is autogenerated via `bin/rails app_config:generate`
      // do not manually edit this file

      export type AppConfigType = {
      #{properties}
      }

      const metaTags = document.querySelectorAll<HTMLMetaElement>("meta[data-config]")
      const config = {} as AppConfigType

      metaTags.forEach((meta) => {
        const name = meta.getAttribute("name")
        const content = meta.getAttribute("content")
        if (name && content !== null) {
          config[name as keyof AppConfigType] = content
        }
      })

      export const AppConfig = config
    TYPESCRIPT

    File.write(output_file, typescript_content)

    puts "Generated TypeScript types at #{output_file}"
  end
end
