default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  <% if ENV["DATABASE_HOST"].present? %>
  host: <%= ENV["DATABASE_HOST"] %>
  <% end %>

development:
  <<: *default
  database: tanooki_prefab_development

test:
  <<: *default
  database: tanooki_prefab_test
